import type { Metadata } from "next";
import LegalLayout from "@/components/LegalLayout";

export const metadata: Metadata = {
  title: "Terms of Service — Aunty Curl Council",
  description: "Terms and conditions for using Aunty Curl Council.",
};

export default function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" lastUpdated="April 16, 2026">
      <p>
        Welcome to Aunty Curl Council. These Terms of Service (&ldquo;Terms&rdquo;)
        govern your access to and use of our website, app, and related services
        (collectively, the &ldquo;Service&rdquo;). By using the Service, you agree
        to these Terms. Please read them carefully.
      </p>

      <h2>1. Who we are</h2>
      <p>
        Aunty Curl Council (&ldquo;we,&rdquo; &ldquo;us,&rdquo; &ldquo;our&rdquo;)
        provides an AI-powered hair care consultation and personalized routine
        service. We are a pre-launch product. Access before public launch is
        offered through our Founding Member program.
      </p>

      <h2>2. What Founding Membership includes</h2>
      <p>
        When you purchase a Founding Member plan, you&rsquo;re paying for early
        access to the Service once it launches, plus the locked-in benefits
        described on the plan you selected. You are <strong>not</strong> purchasing
        a physical product.
      </p>
      <p>
        We aim to deliver the Service within a reasonable timeframe after your
        purchase. If we are unable to launch, you are entitled to a refund as
        described in our <a href="/refund">Refund Policy</a>.
      </p>

      <h2>3. Your responsibilities</h2>
      <ul>
        <li>You must provide accurate information when signing up or purchasing.</li>
        <li>You must be at least 13 years old (or the minimum age in your country) to use the Service.</li>
        <li>You are responsible for keeping your account credentials secure.</li>
        <li>You may not use the Service to harm others, infringe intellectual property, or violate applicable law.</li>
      </ul>

      <h2>4. Health and hair care disclaimer</h2>
      <p>
        Aunty Curl Council provides AI-generated hair care guidance. It is not
        medical advice, dermatological advice, or a substitute for consultation
        with a licensed professional. If you have a scalp condition, allergies,
        or other health concerns, please consult a qualified professional before
        following any recommendation.
      </p>

      <h2>5. Subscriptions and billing</h2>
      <p>
        Founding Member plans are one-time payments for the period described on
        each plan (one month, one year, or lifetime). We use Stripe to process
        payments. By purchasing, you authorize us to charge the payment method
        you provide for the amount shown at checkout.
      </p>

      <h2>6. Refunds</h2>
      <p>
        Our refund terms are described in our <a href="/refund">Refund Policy</a>.
        The short version: if we fail to launch, you get your money back.
      </p>

      <h2>7. Intellectual property</h2>
      <p>
        All content, branding, text, graphics, and AI responses generated by the
        Service are owned by Aunty Curl Council or its licensors. You may use the
        Service for personal, non-commercial purposes only. You may not reproduce,
        resell, or redistribute our content without permission.
      </p>

      <h2>8. Limitation of liability</h2>
      <p>
        To the fullest extent permitted by law, Aunty Curl Council is not liable
        for indirect, incidental, consequential, or punitive damages arising from
        your use of the Service. Our total liability for any claim is limited to
        the amount you paid us in the 12 months preceding the claim.
      </p>

      <h2>9. Termination</h2>
      <p>
        We may suspend or terminate your access if you violate these Terms. You
        may stop using the Service at any time. Termination does not automatically
        entitle you to a refund beyond what&rsquo;s described in our Refund Policy.
      </p>

      <h2>10. Changes to these Terms</h2>
      <p>
        We may update these Terms as the Service evolves. Material changes will be
        communicated by email or on-site notice. Continued use after changes means
        you accept the updated Terms.
      </p>

      <h2>11. Contact</h2>
      <p>
        Questions about these Terms? Email us at{" "}
        <a href="mailto:hello@auntycurlcouncil.com">hello@auntycurlcouncil.com</a>.
      </p>
    </LegalLayout>
  );
}
